name: Build

on:
  push:
    branches:
      - main  # Specificați aici ramura pe care doriți să declanșați acțiunea

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install kivy requests beautifulsoup4 selenium pyopenssl
          python -m pip install buildozer  # Instalează Buildozer
          python -m pip install Cython

      - name: Build with Buildozer
        run: |
          buildozer -v android debug  # Comandă pentru a construi aplicația Android folosind Buildozer

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: downloads  # Schimbă aici calea către directorul în care se află fișierul APK generat
