name: Build

on:
  push:
    branches:
      - main  # Schimbă aici ramura pe care dorești să declanșezi acțiunea

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specifică aici versiunea de Python necesară

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install buildozer  # Instalează Buildozer

      - name: Build with Buildozer
        run: |
          buildozer -v android debug  # Comandă pentru a construi aplicația Android folosind Buildozer

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: downloads  # Schimbă aici calea către directorul în care se află fișierul APK generat
